### ISSUE TITLE
Tracker stops completely with a REL note

### ISSUE THREAD

**Issue by QuietGeckoAudio** [keithclark/ZzFXM#13]
I'm using https://keithclark.github.io/ZzFXM/tracker/?demo

Everything was working great but yesterday any REL note makes the tracker stop.

I'm getting this error when I load the link.

![imagen](https://user-images.githubusercontent.com/40271747/92326506-60ac3000-f018-11ea-88c1-be10ea00822e.png)

and when trying to play a REL note, this stop the tracker

![imagen](https://user-images.githubusercontent.com/40271747/92326556-97824600-f018-11ea-99c1-c36a679689d6.png)

Hopefully is fixable but I just don't know how and was having a lot of fun using it for js13k :(

Thanks!

**Comment by keithclark** [comment]
Thanks for the report. I'll get a fix pushed as soon as I can.

**Comment by QuietGeckoAudio** [comment]
> 
> 
> Thanks for the report. I'll get a fix pushed as soon as I can.

Awesome, Thanks to you!

**Comment by keithclark** [comment]
Fixed and deployed. Could you re-test and let me know if everything works as expected for you now?

**Comment by QuietGeckoAudio** [comment]
> 
> 
> Fixed and deployed. Could you re-test and let me know if everything works as expected for you now?

Yes! Is working as expected now!
Thank you very much!

**Comment by keithclark** [comment]
No problem - and thanks again for taking the time to report the issue.
