### ISSUE TITLE
Optionally migrating tracker into an electron app

### ISSUE THREAD

**Issue by TimSusa** [keithclark/ZzFXM#19]
# Suggestion
- establish another script for package.json to develop/build for the electron desktop app
- the app would build for mac, win and linux
- See example here: https://github.com/TimSusa/midi-bricks-mono better: https://github.com/TimSusa/midi-bricks-mono/blob/master/packages/midi-bricks/package.json
- As starting point some kind of electron.js has to be established: https://github.com/TimSusa/midi-bricks-mono/blob/master/packages/midi-bricks/app/electron.js

**Comment by keithclark** [comment]
Personally, I can't see any benefit to wrapping the tracker up into an Electron app. If anything it could make the development process more complex as there will be more things to maintain and release. 

That said, I'm happy to be convinced. What advantages do you think an electron version would give us vs loading a URL in the browser?

**Comment by TimSusa** [comment]
Hey @keithclark, 

I have this project running by the way: https://github.com/TimSusa/midi-bricks-mono, which is a kind of hypbrid electron app. People, using this are quite happy to have the possibility of being independent about Online or Offline. Imagine some guys are standing in a cellar or tunnel and want to jam with their dudes without relying on having an internet connection. The app does more feel like an native installed application.

**Comment by KilledByAPixel** [comment]
If you download the ZzFXM release you can just open it in a browser to run it offline.

**Comment by keithclark** [comment]
We also have the option of adding a service worker to provide offline support, along with adding a manifest.json so it can be installed as a PWA.

**Comment by TimSusa** [comment]
I can see your point, but electron gives you access to special features like opening the window in a pre-configured setup or location, for example. I am talking about all these small things, which makes your gear better fit into some creative workflows. You have access to the operation system with electron. I mean thats the point. You could even have an auto-updater for latest versions. Build a local server for local connections.. etc pp.

**Comment by TimSusa** [comment]
Yea ok I see... https://www.youtube.com/watch?v=IkdmOVejUlI&t=38s maybe this discussion is out of your scope and I do not have the energy to convince you further. As far as for me you can close this issue. Machts gut!
