### ISSUE TITLE
Piano - Keyboard keys are strange

### ISSUE THREAD

**Issue by caesarsol** [keithclark/ZzFXM#20]
Hi, first of all: awesome project!!

I am just fiddling with the Tracker and I notice the keyboard keys associated to the piano keys are strange: the `5` in `QWE5TYUIOP` part seems out of place.
I understand that the `Z` is the C1, `,` is the C2,  `Q` is an F2, but then `T` is a C3 and `R` should be a semitone under it to make a B3 :) 

Anyway, I was just curious about it and  wanted to know if you made it on purpose, maybe to let the user easily transition to the fourth?

**Comment by keithclark** [comment]
Thanks for reporting this.

It's a bug. The [keyboard map](https://github.com/keithclark/ZzFXM/blob/master/tools/tracker/src/config.js#L14-L20) is incorrect and you're the first person to notice 😄.

The entry for `4` is missing so `R` onward are rendered in the wrong place.

**Comment by keithclark** [comment]
Fixed in https://github.com/keithclark/ZzFXM/pull/21/commits/f5923ca7885c1b547b059473559ab01c3023d012. This will be in the next release.

**Comment by caesarsol** [comment]
Awesome! Yeah I'm told to be picky on details :)
