### ISSUE TITLE
Uncaught DOMException: Failed to execute 'createBuffer' on 'BaseAudioContext'

### ISSUE THREAD

**Issue by jdnichollsc** [keithclark/ZzFXM#23]
Hello mate, thanks for this awesome tool, this project is amazing! <3

I'm testing about `ZzFX Sound Caching` but I'm getting this error:
```
Uncaught DOMException: Failed to execute 'createBuffer' on 'BaseAudioContext': The number of channels provided (27882) is outside the range [1, 32].
    at zzfxP (https://keithclark.github.io/ZzFXM/:213:57)
    at <anonymous>:2:1
```

I'm testing from the github page of this project (Using Chrome):
```
const lazer = zzfxG(...[1.04,,60,.01,.09,.44,,1.61,-5.2,,,,,.3,,.1,,.87,.09]);
zzfxP(...lazer);
```

What do you think?

**Comment by keithclark** [comment]
The example is wrong! You don't need to spread lazer, instead just call `zzfxP(lazer)`

I'll update the example. Thanks taking time to reporting this.

**Comment by keithclark** [comment]
I've just pushed the latest tracker (v1.0.5b) and updated the ZzFXM site so this should be fixed now.

**Comment by jdnichollsc** [comment]
Awesome, thanks mate!

**Comment by jdnichollsc** [comment]
Hello mate, I'm getting this warning from the GitHub page of the project:
`The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.`

I tried again but the audio is not working, I can't hear anything. Check the logs please:
![image](https://user-images.githubusercontent.com/2154886/97525331-8698e580-1974-11eb-9ff7-6b6f87f2a332.png)

What do you think? 🤔
