### ISSUE TITLE
top.AudioContext not working from iframe

### ISSUE THREAD

**Issue by jdnichollsc** [keithclark/ZzFXM#28]
Hello mate,

I was testing this lib from Codepen but it doesn't work.
Please check this [PR](https://github.com/keithclark/ZzFXM/pull/26) to solve this issue.

Best,
Juan

**Comment by jdnichollsc** [comment]
@keithclark sorry, are you planing to create a new release with this little change?

**Comment by keithclark** [comment]
Not just for this small change. There are a few other bug fixes and features that will be merging soon.

**Comment by jdnichollsc** [comment]
Thanks mate!

**Comment by jdnichollsc** [comment]
Still waiting <3

**Comment by jdnichollsc** [comment]
@keithclark hello mate, can you reopen this issue until you publish a new release?
